# Generated by Django 4.0.5 on 2022-06-08 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('resolved', models.DateTimeField(null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_priority', models.BooleanField(default=False)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_set', related_query_name='agent', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_set', related_query_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
